steps:
  # Build the container image with build args for Vite env vars (Firebase)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--no-cache'
      - '--build-arg'
      - 'VITE_FIREBASE_API_KEY=${_VITE_FIREBASE_API_KEY}'
      - '--build-arg'
      - 'VITE_FIREBASE_AUTH_DOMAIN=${_VITE_FIREBASE_AUTH_DOMAIN}'
      - '--build-arg'
      - 'VITE_FIREBASE_PROJECT_ID=${_VITE_FIREBASE_PROJECT_ID}'
      - '--build-arg'
      - 'VITE_FIREBASE_STORAGE_BUCKET=${_VITE_FIREBASE_STORAGE_BUCKET}'
      - '--build-arg'
      - 'VITE_FIREBASE_MESSAGING_SENDER_ID=${_VITE_FIREBASE_MESSAGING_SENDER_ID}'
      - '--build-arg'
      - 'VITE_FIREBASE_APP_ID=${_VITE_FIREBASE_APP_ID}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ai-debatelab:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ai-debatelab:latest'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/ai-debatelab:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/ai-debatelab:latest'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ai-debatelab:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300s'
      - '--concurrency'
      - '80'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '2'
      - '--set-env-vars'
      - 'NODE_ENV=production,DATABASE_URL=${_DATABASE_URL},FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID},FIREBASE_CLIENT_EMAIL=${_FIREBASE_CLIENT_EMAIL},FIREBASE_PRIVATE_KEY=${_FIREBASE_PRIVATE_KEY},OPENROUTER_API_KEY=${_OPENROUTER_API_KEY},ENCRYPTION_KEY=${_ENCRYPTION_KEY},JWT_SECRET=${_JWT_SECRET}'

images:
  - 'gcr.io/$PROJECT_ID/ai-debatelab:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/ai-debatelab:latest'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'

# Substitution variables - set these in Cloud Build trigger settings or pass via GitHub Actions
substitutions:
  _DATABASE_URL: ''
  _VITE_FIREBASE_API_KEY: ''
  _VITE_FIREBASE_AUTH_DOMAIN: ''
  _VITE_FIREBASE_PROJECT_ID: ''
  _VITE_FIREBASE_STORAGE_BUCKET: ''
  _VITE_FIREBASE_MESSAGING_SENDER_ID: ''
  _VITE_FIREBASE_APP_ID: ''
  _FIREBASE_PROJECT_ID: ''
  _FIREBASE_CLIENT_EMAIL: ''
  _FIREBASE_PRIVATE_KEY: ''
  _OPENROUTER_API_KEY: ''
  _ENCRYPTION_KEY: ''
  _JWT_SECRET: ''
