steps:
  # Build the container image
  # Note: Firebase client config is hardcoded in client/src/lib/firebase.ts (public, non-secret values)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--no-cache'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ai-debatelab:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ai-debatelab:latest'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/ai-debatelab:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/ai-debatelab:latest'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ai-debatelab'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ai-debatelab:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300s'
      - '--concurrency'
      - '80'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '2'
      - '--set-env-vars'
      - '^::^NODE_ENV=production::BUILD_ID=$COMMIT_SHA::DATABASE_URL=${_DATABASE_URL}::FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID}::FIREBASE_CLIENT_EMAIL=${_FIREBASE_CLIENT_EMAIL}::FIREBASE_PRIVATE_KEY=${_FIREBASE_PRIVATE_KEY}::FIREBASE_STORAGE_BUCKET=${_FIREBASE_STORAGE_BUCKET}::OPENROUTER_API_KEY=${_OPENROUTER_API_KEY}::ENCRYPTION_KEY=${_ENCRYPTION_KEY}::JWT_SECRET=${_JWT_SECRET}'

images:
  - 'gcr.io/$PROJECT_ID/ai-debatelab:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/ai-debatelab:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  substitution_option: 'ALLOW_LOOSE'

timeout: '1200s'

# Substitution variables - set these in Cloud Build trigger settings or pass via GitHub Actions
substitutions:
  _DATABASE_URL: ''
  _FIREBASE_PROJECT_ID: ''
  _FIREBASE_CLIENT_EMAIL: ''
  _FIREBASE_PRIVATE_KEY: ''
  _FIREBASE_STORAGE_BUCKET: ''
  _OPENROUTER_API_KEY: ''
  _ENCRYPTION_KEY: ''
  _JWT_SECRET: ''